### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by jdwyant8** [connormanning/potree.entwine.io#10]
I don't see information on how to get the project up and running locally.

**Comment by hobu** [comment]
> get the project up and running locally.

It isn't a project to run locally. I'm not sure what you are trying to accomplish.

**Comment by jdwyant8** [comment]
I'm sorry, I guess I don't understand. Why is the code posted if you can't run locally and develop on it?

**Comment by hobu** [comment]
It is just the source tree of the demo website. It isn't a project, and we don't develop on it. What are you trying to accomplish?

**Comment by jdwyant8** [comment]
I'm primarily trying to figure out how to locally view point cloud images and ideally update the image dynamically. I cannot have a separately hosted site like the demo website view the images due to IP.

**Comment by connormanning** [comment]
> Why is the code posted if you can't run locally and develop on it?

This entire repo is simply a set of static pages, so just serve the whole thing with any webserver and browse to the result.

```
cd code/potree.entwine.io
docker run -it -v `pwd`:/var/www -p 8080:8080 connormanning/http-server
```

And then browse to http://localhost:8080.
