### ISSUE TITLE
Displaying multiple EPT clouds in Potree from S3 or other cloud provider

### ISSUE THREAD

**Issue by tyson-swetnam** [connormanning/potree.entwine.io#11]
Hi @connormanning,

Can you help me with a solution for viewing multiple hosted EPT point clouds either in S3 (e.g. https://usgs.entwine.io) or other cloud services (my example, https://data.cyverse.org/dav-anon/iplant/projects/aes/srer/suas/2019/ecostate_mapping/ept/) via a single Potree `.html` file? I found that the USGS Entwine hosting only displays single clouds.

FWIW, I'm trying to show both sUAS (drone) SfM point clouds, co-aligned with aerial lidar clouds in the same Potree `html` with shape files for annotation. 

I've tried out @m-schuetz example for EPT and `laz`: https://github.com/potree/potree/blob/develop/examples/ept.html -- but this relies on locally hosted EPT, rather than S3`http` or `https` EPT -- my example using local clouds here: http://calliope.cyverse.org/pointclouds/potree/examples/ept_four_sites.html

Anyways, thanks again to Howard, you, and Marcus for this awesome software.

**Comment by connormanning** [comment]
The USGS hosting can display multiple point clouds, for example [this link](https://usgs.entwine.io/data/view.html?t=%5B-10129386.23741749,5326607.481430923,32616.786779827904%5D&p=%5B-10129386.23741749,5326607.481430923,1488385.3878386503%5D&r=%5B%22https://s3-us-west-2.amazonaws.com/usgs-lidar-public/IA_FullState%22,%22https://s3-us-west-2.amazonaws.com/usgs-lidar-public/KY_FullState%22,%22https://s3-us-west-2.amazonaws.com/usgs-lidar-public/MN_FullState%22%5D&ir=%5B0,256%5D&era=%5B-1897,2017%5D&cf=%5B7%5D).  You just need to call `loadPointCloud` with the `ept.json` links to all of your point clouds (see [code example](https://github.com/connormanning/potree.entwine.io/blob/master/js/script.js#L401-L404)).  If you have a fixed list of resources you can just do this directly in your setup script.  This repository and the USGS one uses query parameters to allow the specification of multiple resources.
