### ISSUE TITLE
Potree + Entwine authentication towards gs: bucket 

### ISSUE THREAD

**Issue by paujar** [connormanning/potree.entwine.io#13]
Hello!

really love this tool, but I have a problem, I cannot figure out how to setup entwine backend that rests in google buckets with authentication; and to use service accounts to accomplish this (authentication comes from .json file); do you happen to have example how to make it? in the potree+entwine?

**Comment by connormanning** [comment]
This would need to be done in Potree itself, rather than this project which is simply a display of data within Potree.
