### ISSUE TITLE
How to add 360° textured spheres

### ISSUE THREAD

**Issue by RaidCode** [connormanning/potree.entwine.io#5]
Hello, i have .xyz file with somes pictures.
Each lines in .xyz file define : X Y Z Rxx Rxy Rxz Ryx Ryy Ryz Rzx Rzy Rzz 0 Picture_Index
I think i need all of this for add spheres : GPS position, image position...

My questions are :
How to create spheres ?
After, how to precess to add all of my pictures in these spheres ?

Thanks !

**Comment by RaidCode** [comment]
Why you close this issue without answer me ?

**Comment by hobu** [comment]
this ticket is not appropriate for this repository. I don't know where you can get this question answered, but it isn't here.

**Comment by RaidCode** [comment]
Humm, you sure ?
I'm using potree.entwine i don't know where i can get answer about this other than here ...
can you show me the right place ?
Thx

**Comment by matzora** [comment]
https://github.com/mrdoob/three.js/issues

**Comment by RaidCode** [comment]
@matzora Merci Mathieu ;)
