### ISSUE TITLE
New EPT SRS shortcuts are not understood

### ISSUE THREAD

**Issue by adamsteer** [connormanning/potree.entwine.io#9]
Using the new EPT SRS shortcut:

```
"srs" :
	{
		"authority" : "EPSG",
		"horizontal" : "32755",
		"wkt" : “PROJCS[…]"
	},
```

The Potree viewer throws an exception in Proj.4:

![screen shot 2018-11-14 at 9 13 31 am](https://user-images.githubusercontent.com/13084118/48446603-cac56680-e7ed-11e8-9635-88e71be73d4d.jpg)

…and while the point cloud loads, the sidebar is a mess:

![screen shot 2018-11-14 at 9 18 19 am](https://user-images.githubusercontent.com/13084118/48446767-41626400-e7ee-11e8-98ad-657adec15441.jpg)

 
If I remove the new parts and keep only the wkt:

```
"srs" :
	{
		"wkt" : “PROJCS[…]"
	},
```

…everything works just fine. I’m not certain how to dig further here.

**Comment by connormanning** [comment]
I've seen this a number of times and usually just hack away the `srs` entirely to fix it, which of course is extremely hacky and removes the map from the UI entirely.  I think it's an issue with a missing try-catch in Potree from the time I forked (combined with proj4.js not understanding the EPSG code), and I believe it's actually fixed upstream at this point.

Note that this isn't just an issue with EPSG codes - I've seen this with misunderstood WKT as well.

I will merge upstream Potree into my fork in preparation for pull-requesting the EptLoader into Potree, and I'll make sure this behavior is fixed while I'm at it.

Interesting that in your case the code is not understood, but the WKT is.  Maybe the EptLoader should check the code and fall back to the WKT if it's not understood (or the other way around).

**Comment by adamsteer** [comment]
Ah OK. I think EptLoader should try the EPSG code and fall to the WKT if the code is:
- not present
- not understood

for now, I’ll hack around it :)

**Comment by connormanning** [comment]
This should be working now as of f7b61ce, which updates this site to the most recent potree library where there is a fix for unrecognized SRS values.  This has also just been deployed to potree.entwine.io website.  Let me know if there are still issues.
